# permissions for end users to view externalresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalresource-viewer-role
rules:
- apiGroups:
  - sf.statefarm.com
  resources:
  - externalresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sf.statefarm.com
  resources:
  - externalresources/status
  verbs:
  - get
